# Generated by Django 4.1.1 on 2022-09-29 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
